spring.application.name=demo
# logging
logging.level.org.springframework=info

#profiles
# spring.profiles.active=dev

#properties
currency-service.url=http://default.domain.com
currency-service.username=defaultUsername
currency-service.key=defaultkey

#actuator
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,metrics

#h2
# Use a fixed name instead of random UUID
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# Enable H2 console
spring.h2.console.enabled=true

# Optional: customize the path (default is /h2-console)
spring.h2.console.path=/h2-console