spring.application.name=demo
# logging
logging.level.org.springframework=debug

#profiles
spring.profiles.active=prod

#properties
currency-service.url=http://default.domain.com
currency-service.username=defaultUsername
currency-service.key=defaultkey

#actuator
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,metrics