spring.application.name=demo
logging.level.org.springframework=debug
spring.profiles.active=prod

currency-service.url=http://default.domain.com
currency-service.username=defaultUsername
currency-service.key=defaultkey